### ISSUE TITLE
About the image morphing

### ISSUE THREAD

**Issue by awecefil** [kfiraberman/neural_best_buddies#13]
Hello, I want to thank you for giving this research and result. It is a very powerful method.
And I am interested in the image morphing process, so could you release the code about the image morphing process? 
Thanks

**Comment by AradMerp** [comment]
Hi @awecefil  @kfiraberman  did you find/write the code for image morphing? If so can you please share it.

thanks!

**Comment by kfiraberman** [comment]
Hi, yes, we will upload it soon (probably by next week).

**Comment by AradMerp** [comment]
@kfiraberman  thank you very much, it would be great if you can upload it as early as possible, kind of urgent.
thanks once again!

**Comment by kfiraberman** [comment]
It will take me a few days to organize and upload it. If it is urgent, you can contact me by email kfiraberman@gmail.com and I will send you everything rightaway. @AradMerp

**Comment by kubmin** [comment]
Hi, any updates on the image morphing code?
Thanks!

**Comment by kfiraberman** [comment]
Done. (Instruction were added to the readme file).
