### ISSUE TITLE
How to use CPU  run this program? 

### ISSUE THREAD

**Issue by antoniolq** [kfiraberman/neural_best_buddies#6]
Dear pro:
Hello, I download this and try to run it,but it seem use GPU acceleration by default. it met an error "RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74
 " 
My pc only support cpu env?could you tell me how to switch it?Thank you！

**Comment by rch850** [comment]
Have you tried command line option `--gpu_ids -1`? `python3 main.py --help` prints following:

```
  --gpu_ids GPU_IDS     gpu ids: e.g. 0 0,1,2, 0,2. use -1 for CPU
```
