### ISSUE TITLE
Out of range of index when warping

### ISSUE THREAD

**Issue by y123214** [kfiraberman/neural_best_buddies#8]
Why I usually get Out of range of index when warping error, when running mlsd_2d_warp function??

**Comment by Shimingyi** [comment]
HI y123214,

For better decoupling, you can run **_run_MLS_in_folder_** function directly after you got the  **_correspondence_*.txt_** files. It's easy to use and you can find more details in _**./utils/MLS.py**_.

If you still get errors, you can upload your correspondence file to here, we can check it.

**Comment by jackkun303** [comment]
I got the same issue wen running interp2; report xp and fp are not of the same length ( line 39)

**Comment by Shimingyi** [comment]
> I got the same issue wen running interp2; report xp and fp are not of the same length ( line 39)

Hi jackkun303,

Thanks for your feedback, I reproduced your error in python2.x and now pull a new request to fix the error. 

The issue will be closed.
